graph TD
A["Laptop (Tidal Cycles + Software Synth)"] <-->|"USB (MIDI + Audio)"| B[UR242]
B -->|MIDI| C[Synth Korg Volca Keys]
C -->|Audio| B[Interface UR242]
B -->|Audio| D[Lautsprecher]
E[MIDI Controller] -->|"USB (MIDI)"| A 
